name: MYCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  firstjob:
    steps:
      # checkout your respository
      - uses: actions/checkout@v3
    
      run: |
        echo hello
        echo done
