name: MYCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  firstjob:
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      run: |
        echo hello
        echo done
