name: MYCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  firstjob:
    runs-on: ubuntu-latest
    # checkout your respository
    steps:
      - uses: actions/checkout@v3
    
      run: |
        echo hello
        echo done
