# This is a basic workflow to help you get started with Actions

name: container-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env: 
        NODE_ENV: development
      ports:
        - 80
      volumes: 
        - my_docker_volumn:/volumn_amount
      options: --cpus 1
      
    steps:
      - name: first step
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
  
