# This is a basic workflow to help you get started with Actions

name: MYCI

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      fieldname:
        description: 'A username passed from the caller workflow'
        default: 'abxxx'
        required: false
        type: string
        
jobs:
  first:
    runs-on: ubuntu-latest
    
    steps:
      - name: print from param
        run: |
          echo this is from param {{fieldname}}

