# This is a basic workflow to help you get started with Actions

name: services-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  service-job:
    runs-on: 	ubuntu-latest
    steps:
      - name: first step
        run: | 
          echo curl http://localhost:80
    services:
      nginx: 
        image: nginx
        ports: 
          - 8080:80
      redis:
        image: redis
        ports:
          - 6379/tcp
        
    
