name: Greeting from Mona

on: 
  push: 
    branches: 
      - main

jobs:
  myjob:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: hello
          FIRST_NAME: OSWIN
          LAST_NAME: WANG
        run: |
          echo $MY_VAR, $FIRST_NAME, $LAST_NAME.
      
      - name: next step
        if: ${{ success() }}
        run: |
          echo this is series, ok.
          
      - name: third step
        uses: docker://alpine:3.8
        
      - name: 4th step
        run: echo $PATH
        shell: bash
        continue-on-error: true
      
      - name: 5th step
        run: |
          import os
          print(os.environ['PATH'])
        shell: python
      
      - name: 6th step
        run: |
          echo 6th
          
      # Reference a specific commit
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      # Reference the major version of a release
      - uses: actions/checkout@v3
      # Reference a specific version
      - uses: actions/checkout@v3.2.0
      # Reference a branch
      - uses: actions/checkout@main
